/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/scene.gltf
Author: MADE.COM (https://sketchfab.com/made-it)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/doris-armchair-shetland-moss-42c994174d6542c195f0c6690dc370ec
Title: Doris Armchair, Shetland Moss
*/

import React from "react";
import { Decal, useGLTF, useTexture } from "@react-three/drei";

export function Chair001(props) {
  const { nodes, materials } = useGLTF("./models/scene.gltf");

  return (
    <group {...props}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          geometry={nodes.Doris_Armchair_FABRIC_0.geometry}
          material={materials.FABRIC}
        ></mesh>
        <mesh
          geometry={nodes.Doris_Armchair_WOOD_0.geometry}
          material={materials.WOOD}
        />
      </group>
    </group>
  );
}

useGLTF.preload("./models/scene.gltf");
